"""add source_label to articles

Revision ID: d40db164e75f
Revises: cb6f2ed3b7a0
Create Date: 2026-04-17 22:16:18.942054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40db164e75f'
down_revision: Union[str, None] = 'cb6f2ed3b7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_label', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'source_label')
    # ### end Alembic commands ###
